name: 'tagged-release'

on:
  push:
    tags:
      - 'v*'

jobs:
  gh_tagged_release:
    runs-on: 'ubuntu-latest'

    permissions: write-all

    # strategy:
    #   matrix:
    #     node-version: [18.x]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      # - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #     cache: 'npm'

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: electronuserland/builder:wine
          options: -v ${{ github.workspace }}:/project
          run: |
            npm ci
            npm run build:win

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            dist/*.deb
            dist/*.snap
            dist/*.AppImage
            dist/*.exe
        id: 'automatic_releases'
