name: 'tagged-release'

on:
  push:
    tags:
      - 'v*'

jobs:
  gh_tagged_release:
    runs-on: 'ubuntu-latest'

    permissions: write-all

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build:win
      - run: npm run build:linux

      - uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          files: |
            dist/*.deb
            dist/*.snap
            dist/*.AppImage
        id: 'automatic_releases'
